add function namify
js-tasks-ru/jsbasic-20241021_vilenan pull request #3
Opened 2024-11-05 12:43 UTC by vilenan

2024-11-05 12:44 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-05 13:35 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-11-05 17:44 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-11-06 13:06 UTC, SinimaWath requested changes

2024-11-06 13:06 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return a + restArrString;
тут переусложнение, проверять, что это первый елемент нужно/можно прямо в map:

```
arr.map((value, index) => index === 0 ? ... : ...)
```

И еще давай стрелочную функцию использовать

2024-11-08 05:10 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-08 15:53 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-11-09 15:16 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-11-09 15:43 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-11-10 18:39 UTC, SinimaWath approved these changes

2024-11-10 18:40 UTC, merged